import { Footer } from '@/src/components/Footer';
import { Header } from '@/src/components/Header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={'antialiased flex flex-col items-center justify-items-center min-h-screen gap-16'}
      >
        <div className={'max-w-[1200px] min-w-[360px] w-full mx-auto mt-3 mb-3 flex flex-col items-center'} >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
